- name: Run backups
  user: ubuntu
  hosts: webserver
  roles:
    - run_backups

- name: Deploys a project update
  user: ubuntu
  hosts: webserver
  roles:
    - deploy_rbhl

- name: Set up backups
  user: ubuntu
  hosts: webserver
  roles:
    - setup_backups

- name: Restart services
  user: ubuntu
  hosts: webserver
  roles:
    - restart
