- name: Creates backup dir
  become: true
  file:
    path: "{{ BACKUPS_DIR }}"
    state: directory
    owner: ubuntu
    mode: 0741

- name: Create the backup script
  become: yes
  template:
    src: "templates/backup.sh.jinja2"
    dest: "{{ PROJECT_PATH }}/scripts/backup.sh"
    owner: ubuntu
    mode: 0741

- name: Create the s3 secret key
  become: yes
  template:
    src: "templates/s3_secret.jinja2"
    dest: "{{ PROJECT_PATH }}/scripts/s3_secret"
    owner: ubuntu
    mode: 0741

- name: Creates backups dir
  file:
    path: "{{ BACKUPS_DIR }}"
    state: directory

- name: Creates AWS dir
  file:
    path: /home/ubuntu/.aws
    state: directory

- name: create AWS credentials
  template:
    src: templates/aws_credentials.ini
    dest: /home/ubuntu/.aws/credentials

- name: create AWS config
  template:
    src: templates/aws_config.ini
    dest: /home/ubuntu/.aws/config

- name: fire the backup cron
  cron:
    name: "backup"
    minute: "0"
    hour: "20"
    user: "ubuntu"
    job: "{{ PROJECT_PATH }}/scripts/backup.sh"
